Add lxml to pip-requires
Without this, I was getting:

  ERROR: Failure: ImportError (No module named lxml)
  ...
  ImportError: No module named lxml
  ...
  ERROR: test_versions_index (melange.tests.unit.test_versions.TestVersionsController)
  ...
  Got: ImportError('No module named lxml',)
  ...
  ERROR: test_versions_index_for_xml (melange.tests.unit.test_versions.TestVersionsController)
  Got: ImportError('No module named lxml',)

Change-Id: I73eac14526d4ea5991b5d7186d42208a4c230569