Fix 047 migration with SQLAlchemy 0.7.2
In 0.6.3, foreign_keys was an OrderedSet which can be indexed. In 0.7.2
it's a plain old set which can't be indexed.

  File ".../nova/db/sqlalchemy/migrate_repo/versions/047_remove_instances_fk_from_vif.py", line 35, in upgrade
      fkey_name = vifs.c.instance_id.foreign_keys[0].constraint.name
  TypeError: 'set' object does not support indexing

Change-Id: I8d6378d2fd25f7659d6a6469de762728639cc4ad